# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='image',
            field=models.ImageField(upload_to='static/uploads'),
        ),
    ]
